#!/usr/bin/env bash
# Usage: scienv completions <command> [arg1 arg2...]

set -e
[ -n "$ANYENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  scienv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "scienv-$COMMAND" || command -v "scienv-sh-$COMMAND")"
if grep -i "^\([#%]\|--\|//\) provide scienv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
