#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export SCIENV_DEBUG=1
  shift
fi

if [ -n "$SCIENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "scienv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${SCIENV_ROOT}" ]; then
  SCIENV_ROOT="${HOME}/.scienv"
else
  SCIENV_ROOT="${SCIENV_ROOT%/}"
fi
export SCIENV_ROOT

if [ -z "${SCIENV_DIR}" ]; then
  SCIENV_DIR="$(pwd)"
else
  cd "$SCIENV_DIR" 2>/dev/null || {
    echo "scienv: cannot change working directory to \`$SCIENV_DIR'"
    exit 1
  } >&2
  SCIENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export SCIENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${SCIENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${SCIENV_HOOK_PATH}:${SCIENV_ROOT}/scienv.d:/usr/local/etc/scienv.d:/etc/scienv.d:/usr/lib/scienv/hooks"
for plugin_hook in "${SCIENV_ROOT}/plugins/"*/etc/scienv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export SCIENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(scienv---version)\n$(scienv-help)" >&2
  ;;
"-v" )
  exec scienv---version
  ;;
* )
  command_path="$(command -v "scienv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "scienv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
