#!/usr/bin/env bash
# Summary: List all Any versions available to **env
# Usage: scienv versions
#
# Lists all Any versions found in `$ANYENV_ROOT/envs/*'.

set -e
[ -n "$ANYENV_DEBUG" ] && set -x

for env in $(scienv-envs); do
  echo "$env:"
  if [ "$env" = "erlenv" ]; then
    echo "$($env releases)"
  else
    echo "$($env versions)"
  fi
done
