#!/usr/bin/env bash
# Summary: List all Env versions available to **env
# Usage: scienv versions
#
# Lists all Env versions found in `$SCIENV_ROOT/envs/*'.

set -e
[ -n "$SCIENV_DEBUG" ] && set -x

for env in $(scienv-envs); do
  echo "$env:"
  if [ "$env" = "erlenv" ]; then
    echo "$($env releases)"
  else
    echo "$($env versions)"
  fi
done
