#!/usr/bin/env bash
# Summary: List all **envs available to scienv
# Usage: scienv envs
#
# Lists all **env versions found in `$SCIENV_ROOT/envs/*'.

set -e
[ -n "$SCIENV_DEBUG" ] && set -x

for path in "${SCIENV_ROOT}/envs/"*; do
  if [ -d "$path" ]; then
    echo "${path##*/}"
  fi
done
