#!/usr/bin/env bash
# Summary: Show the current Env version and its origin
#
# Shows the currently selected Env version and how it was
# selected. To obtain only the version string, use `scienv
# version-name'.

set -e
[ -n "$SCIENV_DEBUG" ] && set -x

for env in $(scienv-envs); do
  echo "$env: $($env version)"
done
