#!/usr/bin/env bash
#
# Summary: Show the local application-specific Env version
#
# Shows the local application-specific Env version by writing the
# version name to a file named `.bio-version'.

set -e
[ -n "$SCIENV_DEBUG" ] && set -x

for env in $(scienv-envs); do
  echo "$($env local)"
done
