#!/usr/bin/env bash
#
# Summary: Show the global Env version
#
# Show the global Env version.

set -e
[ -n "$SCIENV_DEBUG" ] && set -x

for env in $(scienv-envs); do
  echo "$env: $($env global)"
done
